In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
#reading the data
df=pd.read_csv("TDHospital/TD_HOSPITAL_TRAIN.csv")

In [3]:
df.head()

,timeknown,cost,reflex,sex,blood,bloodchem1,bloodchem2,temperature,race,heart,psych1,glucose,psych2,dose,psych3,bp,bloodchem3,confidence,bloodchem4,comorbidity,totalcost,breathing,age,sleep,dnr,bloodchem5,pdeath,meals,pain,primary,psych4,disability,administratorcost,urine,diabetes,income,extraprimary,bloodchem6,education,psych5,psych6,information,cancer,death
0,4.0,3008.38867,11.228005,male,20.699219,2.199707,1.299805,35.59375,white,103.0,4.0,157.0,2.0,5,0.0,107.0,0.399963,4.403557,12.0,6.0,2471.7988,34.0,76.56396,7.519531,dnr before sadm,7.359375,NaN,142.0,2.0,Cirrhosis,NaN,<2 mo. follow-up,3525.0,5360.0,0.0,$11-$25k,COPD/CHF/Cirrhosis,167.5000,20.0,30.0,2.000,0.0,no,1.0
1,467.0,23585.89060,9.714861,M,9.398438,NaN,0.699951,39.00000,white,50.0,3.0,271.0,1.0,5,0.0,105.0,NaN,20.260360,10.0,1.0,20651.7812,26.0,63.33499,7.479492,no dnr,7.509766,NaN,132.0,3.0,Colon Cancer,0.0,NaN,43200.0,2570.0,0.0,>$50k,Cancer,480.0000,16.0,11.5,1.000,10.0,metastatic,1.0
2,533.0,4046.45898,11.353296,Male,19.296875,NaN,1.599854,38.19531,white,50.0,3.0,117.0,0.0,5,0.0,73.0,NaN,10.153806,28.0,3.0,4113.6797,13.0,70.52698,NaN,no dnr,7.459961,NaN,131.0,1.0,ARF/MOSF w/Sepsis,1.0,no(M2 and SIP pres),5894.0,1690.0,1.0,under $11k,ARF/MOSF,177.1250,5.0,18.0,0.000,5.0,yes,0.0
3,68.0,NaN,9.269058,female,7.500000,2.500000,0.599976,37.59375,white,80.0,4.0,NaN,NaN,5,0.0,120.0,3.699707,26.700676,NaN,1.0,9094.3281,18.0,55.31799,7.379883,no dnr,NaN,NaN,121.0,1.0,Cirrhosis,2.0,NaN,16717.0,NaN,0.0,$11-$25k,COPD/CHF/Cirrhosis,NaN,12.0,7.0,1.839,12.0,no,1.0
4,1605.0,6457.70703,8.655387,female,15.099609,4.399414,0.699951,35.69531,white,114.0,4.0,NaN,6.0,5,0.0,130.0,0.399963,9.962359,NaN,2.0,7150.9766,28.0,67.06598,7.429688,no dnr,7.449219,NaN,133.0,4.0,COPD,5.0,no(M2 and SIP pres),10151.0,NaN,0.0,under $11k,COPD/CHF/Cirrhosis,233.3125,2.0,7.0,6.000,12.0,no,0.0

In [4]:
print(df.isnull().sum())

timeknown               0
cost                 2705
reflex                  0
sex                     0
blood                 161
bloodchem1           2591
bloodchem2             44
temperature             0
race                   32
heart                   0
psych1                  0
glucose              3525
psych2               2245
dose                    0
psych3                  0
bp                      0
bloodchem3           2012
confidence            166
bloodchem4           3403
comorbidity             0
totalcost             687
breathing               0
age                     0
sleep                1792
dnr                    26
bloodchem5           1749
pdeath               7058
meals                   0
pain                    0
primary                 0
psych4               4334
disability           1102
administratorcost     139
urine                3794
diabetes                0
income               2275
extraprimary            0
bloodchem6           1793
education            1219
psych5                 60
psych6                  0
information            24
cancer                  0
death                   0
dtype: int64

In [5]:
#droping cols which contains large number of missing values 
drop_cols=['cost','bloodchem1','glucose','psych2','bloodchem3','bloodchem4','sleep','bloodchem5','pdeath','psych3','psych4','disability','urine','income','bloodchem6','education']
df.drop(columns=drop_cols, inplace=True)

In [6]:
#replace sex values 
df['sex'] = df['sex'].replace({'male': 'Male','M': 'Male', '1': 'Male', 'female': 'Female'})
df['sex'] = df['sex'].replace({'Male': '1','Female': '0'})

In [7]:
print(df.isnull().sum())

timeknown              0
reflex                 0
sex                    0
blood                161
bloodchem2            44
temperature            0
race                  32
heart                  0
psych1                 0
dose                   0
bp                     0
confidence           166
comorbidity            0
totalcost            687
breathing              0
age                    0
dnr                   26
meals                  0
pain                   0
primary                0
administratorcost    139
diabetes               0
extraprimary           0
psych5                60
psych6                 0
information           24
cancer                 0
death                  0
dtype: int64

In [8]:
##filling null values - blood
def mean_val(column_name):
    mean_value = df[column_name].mean()
    df[column_name].fillna(mean_value, inplace=True)
    return 

mean_cols = ['blood','information','bloodchem2','confidence','totalcost','administratorcost','psych5']
for i in mean_cols:
    mean_val(i)
#     'blood','information','bloodchem2','confidence','totalcost','administratorcost','psych5'

In [9]:
df['psych5'].mean()

22.542951563589593

In [10]:
def mode_val(column_name):
    mode_race = df[column_name].mode()[0]
    df[column_name].fillna(mode_race, inplace=True)
    return 
    
# 'race','dnr'

In [11]:
mode_cols=['race','dnr']
for i in mode_cols:
    mode_val(i)

In [12]:
df.shape

(7058, 28)

In [13]:
#Drop duplicates 
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(7012, 28)

In [15]:
import pandas as pd

# Define a function to find outliers using IQR
def find_outliers_iqr(data_series):
    q1 = data_series.quantile(0.25)
    q3 = data_series.quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = data_series[(data_series < lower_bound) | (data_series > upper_bound)]
    return outliers

# Loop through columns and print the count of outliers
for column in df.columns:
    if pd.api.types.is_numeric_dtype(df[column]):  # Check if the column contains numeric data
        outliers = find_outliers_iqr(df[column])
        if not outliers.empty:
            print(f"Column: {column}, Number of Outliers: {outliers.shape[0]}")

Column: timeknown, Number of Outliers: 189
Column: reflex, Number of Outliers: 53
Column: blood, Number of Outliers: 330
Column: bloodchem2, Number of Outliers: 743
Column: temperature, Number of Outliers: 101
Column: heart, Number of Outliers: 34
Column: psych1, Number of Outliers: 25
Column: bp, Number of Outliers: 6
Column: confidence, Number of Outliers: 327
Column: comorbidity, Number of Outliers: 22
Column: totalcost, Number of Outliers: 709
Column: breathing, Number of Outliers: 228
Column: age, Number of Outliers: 275
Column: meals, Number of Outliers: 198
Column: pain, Number of Outliers: 73
Column: administratorcost, Number of Outliers: 713
Column: diabetes, Number of Outliers: 1351
Column: psych5, Number of Outliers: 43
Column: information, Number of Outliers: 630

In [16]:
def reduce_outliers(values):
    v=[]
    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    for val in values:
        if val>upper_bound:
            v.append(upper_bound)
        elif val<lower_bound:
            v.append(lower_bound)
        else:
            v.append(val)
    return v

In [17]:
# columns=['timeknown','blood','bloodchem2','confidence','totalcost','administratorcost','information','age','psych4','reflex','breathing','meals','temperature']
# for col in columns:
#     v=reduce_outliers(df[col])
#     df[col]=v

In [18]:
# drop_cols=['primary','dnr','extraprimary']

# df.drop(columns=drop_cols, inplace=True)

In [19]:
import pandas as pd
from itertools import combinations
from scipy.stats import chi2_contingency

def chi_square_association_test(df):

    categorical_columns = df.select_dtypes(include=['object']).columns  # Select categorical columns

    for col1, col2 in combinations(categorical_columns, 2):
        contingency_table = pd.crosstab(df[col1], df[col2])
        chi2, p, _, _ = chi2_contingency(contingency_table)

        print(f"Chi-Square Test for {col1} and {col2}:")
        print(f"Chi-Square Value: {chi2}")
        print(f"P-Value: {p}")

        alpha = 0.05  
        if p < alpha:
            print("There is a significant association between the columns.")
        else:
            print("There is no significant association between the columns.")
        print("\n")


chi_square_association_test(df)

Chi-Square Test for sex and race:
Chi-Square Value: 21.720693551342485
P-Value: 0.00022777639283258
There is a significant association between the columns.


Chi-Square Test for sex and dnr:
Chi-Square Value: 27.191902749104447
P-Value: 1.2455275603452506e-06
There is a significant association between the columns.


Chi-Square Test for sex and primary:
Chi-Square Value: 56.362183540551996
P-Value: 8.00296476435994e-10
There is a significant association between the columns.


Chi-Square Test for sex and extraprimary:
Chi-Square Value: 31.319382740019844
P-Value: 7.280906112664189e-07
There is a significant association between the columns.


Chi-Square Test for sex and cancer:
Chi-Square Value: 4.353777315877817
P-Value: 0.11339378922368643
There is no significant association between the columns.


Chi-Square Test for race and dnr:
Chi-Square Value: 32.634447919673164
P-Value: 7.166247719229576e-05
There is a significant association between the columns.


Chi-Square Test for race and primary:
Chi-Square Value: 108.14629202415605
P-Value: 2.328596410954675e-11
There is a significant association between the columns.


Chi-Square Test for race and extraprimary:
Chi-Square Value: 58.11618354062329
P-Value: 4.9656714324493545e-08
There is a significant association between the columns.


Chi-Square Test for race and cancer:
Chi-Square Value: 42.701865900888265
P-Value: 9.995877211616575e-07
There is a significant association between the columns.


Chi-Square Test for dnr and primary:
Chi-Square Value: 568.6477585593744
P-Value: 2.4801911242717616e-112
There is a significant association between the columns.


Chi-Square Test for dnr and extraprimary:
Chi-Square Value: 334.493743654755
P-Value: 3.2846249891126386e-69
There is a significant association between the columns.


Chi-Square Test for dnr and cancer:
Chi-Square Value: 82.76842734880744
P-Value: 4.510954989371234e-17
There is a significant association between the columns.


Chi-Square Test for primary and extraprimary:
Chi-Square Value: 18253.28677999739
P-Value: 0.0
There is a significant association between the columns.


Chi-Square Test for primary and cancer:
Chi-Square Value: 5977.455304313281
P-Value: 0.0
There is a significant association between the columns.


Chi-Square Test for extraprimary and cancer:
Chi-Square Value: 4689.735443599803
P-Value: 0.0
There is a significant association between the columns.

In [20]:
df['race'] = df['race'].replace({'white': '1','black': '0','hispanic':'2','other':'4','asian':'3'})
df['cancer'] = df['cancer'].replace({'yes': '1','no': '0','metastatic':'2'})
df['dnr'] = df['dnr'].replace({'dnr before sadm': '0','no dnr': '1','dnr after sadm':'2'})
df['primary'] = df['primary'].replace({'Cirrhosis': '0','Colon Cancer': '1','ARF/MOSF w/Sepsis':'2', 'COPD':'3','Lung Cancer':'4','MOSF w/Malig':'5', 'CHF':'6','Coma':'7'})
df['extraprimary'] = df['extraprimary'].replace({'COPD/CHF/Cirrhosis': '0','Cancer': '1','ARF/MOSF':'2','Coma':'3'})

In [21]:
df.head()

,timeknown,reflex,sex,blood,bloodchem2,temperature,race,heart,psych1,dose,bp,confidence,comorbidity,totalcost,breathing,age,dnr,meals,pain,primary,administratorcost,diabetes,extraprimary,psych5,psych6,information,cancer,death
0,4.0,11.228005,1,20.699219,1.299805,35.59375,1,103.0,4.0,5,107.0,4.403557,6.0,2471.7988,34.0,76.56396,0,142.0,2.0,0,3525.0,0.0,0,30.0,2.000,0.0,0,1.0
1,467.0,9.714861,1,9.398438,0.699951,39.00000,1,50.0,3.0,5,105.0,20.260360,1.0,20651.7812,26.0,63.33499,1,132.0,3.0,1,43200.0,0.0,1,11.5,1.000,10.0,2,1.0
2,533.0,11.353296,1,19.296875,1.599854,38.19531,1,50.0,3.0,5,73.0,10.153806,3.0,4113.6797,13.0,70.52698,1,131.0,1.0,2,5894.0,1.0,2,18.0,0.000,5.0,1,0.0
3,68.0,9.269058,0,7.500000,0.599976,37.59375,1,80.0,4.0,5,120.0,26.700676,1.0,9094.3281,18.0,55.31799,1,121.0,1.0,0,16717.0,0.0,0,7.0,1.839,12.0,0,1.0
4,1605.0,8.655387,0,15.099609,0.699951,35.69531,1,114.0,4.0,5,130.0,9.962359,2.0,7150.9766,28.0,67.06598,1,133.0,4.0,3,10151.0,0.0,0,7.0,6.000,12.0,0,0.0

In [22]:
numeric_cols=['timeknown','reflex','blood','bloodchem2','temperature','heart','psych1','bp','confidence','comorbidity','totalcost','breathing','age','meals','administratorcost','psych5','psych6','information']

In [23]:
len(numeric_cols)

18

In [24]:
X_train=df[numeric_cols].values

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [26]:
from sklearn.decomposition import PCA
import numpy as np

# Step 1: Preprocess the data (standardization)
# Assuming X contains your data
# Step 2: Compute the covariance matrix

cov_matrix = np.cov(X_train, rowvar=False)

# Step 3: Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Step 4: Sort eigenvalues in descending order
eigenvalue_index = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[eigenvalue_index]
eigenvectors = eigenvectors[:, eigenvalue_index]

# Step 5: Calculate explained variance and decide the number of components
explained_variance = np.cumsum(eigenvalues) / np.sum(eigenvalues)

# Step 6: Choose the number of components to preserve more than 90% of information
n_components = np.argmax(explained_variance >= 0.9999999) + 1

# Step 7: Perform PCA with the selected number of components
pca = PCA(n_components=n_components)
X_train_pca = pca.fit_transform(X_train)

# Now X_pca contains your data with reduced dimensionality.

In [27]:
X_train_pca.shape

(7012, 6)

In [36]:
import pickle
with open('pca.pkl', 'wb') as file:
    pickle.dump(pca, file)

In [28]:
for i in range(X_train_pca.shape[1]):
    df[str(i)+'_pca']=X_train_pca[:,i]

In [29]:
df

,timeknown,reflex,sex,blood,bloodchem2,temperature,race,heart,psych1,dose,bp,confidence,comorbidity,totalcost,breathing,age,dnr,meals,pain,primary,administratorcost,diabetes,extraprimary,psych5,psych6,information,cancer,death,0_pca,1_pca,2_pca,3_pca,4_pca,5_pca
0,4.0,11.228005,1,20.699219,1.299805,35.59375,1,103.0,4.0,5,107.0,4.403557,6.0,2471.7988,34.0,76.56396,0,142.0,2.0,0,3525.000,0.0,0,30.0,2.000000,0.0,0,1.0,-62407.948473,-9201.908255,-484.424964,13.224850,18.595713,9.873131
1,467.0,9.714861,1,9.398438,0.699951,39.00000,1,50.0,3.0,5,105.0,20.260360,1.0,20651.7812,26.0,63.33499,1,132.0,3.0,1,43200.000,0.0,1,11.5,1.000000,10.0,2,1.0,-19028.910204,-4419.282784,-18.262031,-39.105160,31.905243,-6.737283
2,533.0,11.353296,1,19.296875,1.599854,38.19531,1,50.0,3.0,5,73.0,10.153806,3.0,4113.6797,13.0,70.52698,1,131.0,1.0,2,5894.000,1.0,2,18.0,0.000000,5.0,1,0.0,-59642.901919,-8387.967466,44.625924,-46.475510,-1.077993,-3.705715
3,68.0,9.269058,0,7.500000,0.599976,37.59375,1,80.0,4.0,5,120.0,26.700676,1.0,9094.3281,18.0,55.31799,1,121.0,1.0,0,16717.000,0.0,0,7.0,1.839000,12.0,0,1.0,-47802.700326,-7063.365439,-419.378480,-5.338146,40.018072,-11.897877
4,1605.0,8.655387,0,15.099609,0.699951,35.69531,1,114.0,4.0,5,130.0,9.962359,2.0,7150.9766,28.0,67.06598,1,133.0,4.0,3,10151.000,0.0,0,7.0,6.000000,12.0,0,0.0,-54646.906392,-6842.787062,1116.550018,30.101862,35.562398,10.574600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7053,841.0,10.897551,0,15.099609,0.899902,38.00000,0,150.0,5.0,5,131.0,17.303580,2.0,17630.4688,8.0,88.91199,1,134.0,2.0,7,43891.000,0.0,3,17.0,5.000000,11.0,0,0.0,-19323.025133,-7504.437311,356.936478,59.185632,28.126475,33.770860
7054,258.0,10.325173,1,7.500000,0.899902,37.59375,1,112.0,4.0,5,61.0,14.248111,1.0,59733.1875,40.0,59.58398,1,141.0,3.0,5,106109.000,0.0,2,24.5,0.000000,48.0,2,1.0,52977.980941,12898.562097,-226.959262,7.602509,-22.918581,-7.493544
7055,1325.0,9.838906,0,35.000000,0.599976,36.59375,1,126.0,3.0,5,74.0,6.611884,2.0,13303.3438,10.0,61.43500,1,144.0,3.0,3,21128.000,0.0,0,32.5,0.000000,11.0,0,0.0,-42292.100793,-4454.232008,836.656731,28.233343,-21.457077,-0.829572
7056,4.0,9.141439,1,18.199219,0.899902,39.29688,1,132.0,1.0,5,119.0,6.590617,1.0,15496.0078,12.0,51.56699,2,138.0,2.0,7,22312.328,0.0,3,32.0,2.317871,3.0,1,1.0,-40478.224852,-2745.823356,-484.817339,44.826210,25.069924,-10.200893
7057,14.0,11.006892,0,12.599609,0.699951,38.50000,1,114.0,0.0,5,73.0,36.342584,2.0,4007.1875,26.0,60.04898,1,134.0,2.0,3,5874.000,0.0,0,8.0,5.000000,7.0,0,1.0,-59695.308289,-8483.014674,-474.321179,16.260371,-14.541617,-8.339390

In [30]:
df.drop(numeric_cols,axis=1,inplace=True)

In [31]:
train_data=df.drop(['death'],axis=1).values
train_label=df['death']
# X = train_data
# y = train_label
# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
!pip install xgboost

Requirement already satisfied: xgboost in /Users/pragatin/anaconda3/lib/python3.11/site-packages (2.0.1)
Requirement already satisfied: numpy in /Users/pragatin/anaconda3/lib/python3.11/site-packages (from xgboost) (1.24.3)
Requirement already satisfied: scipy in /Users/pragatin/anaconda3/lib/python3.11/site-packages (from xgboost) (1.10.1)

In [33]:
# import xgboost as xgb
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score, classification_report
# X = train_data
# y = train_label
# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# # Create an XGBoost classifier
# xgb_classifier = xgb.XGBClassifier()

# # Train the classifier on the training data
# xgb_classifier.fit(X_train, y_train)

# # Make predictions on the test data
# y_pred = xgb_classifier.predict(X_val)

# # Calculate accuracy
# accuracy = accuracy_score(y_val, y_pred)
# print("Accuracy:", accuracy)

In [34]:
X = train_data
y = train_label

# Split the data into a training and testing set
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8638631503920171

In [38]:
df.shape

(7012, 16)

In [35]:
clf.predict_proba(X[0].reshape(1,27))[0][0]

ValueError: cannot reshape array of size 15 into shape (1,27)

In [ ]:
X[0].shape

In [ ]:
# xgb_classifier.predict_proba(X[56].reshape(1,27))[0][0]

In [39]:
import pickle
with open('RF.pkl', 'wb') as file:
    pickle.dump(clf, file)